import Navagation from '@/app/_components/Navagation';
import Logo from '@/app/_components/Logo';

import '@/app/_styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-blue-900 text-gray-50 min-h-screen'>
        <header>
          <Logo />
          <Navagation />
        </header>
        <main>{children}</main>
        <footer>Copyright by Wild App</footer>
      </body>
    </html>
  );
}
