import Navagation from './components/Navagation';
import Logo from './components/Logo';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <header>
          <Logo />
          <Navagation />
        </header>
        <main>{children}</main>
        <footer>Copyright by Wild App</footer>
      </body>
    </html>
  );
}
